language: php

php:
  - 5.5
  - 5.6
  - hhvm

script:
 - composer install --prefer-source
 - phpunit --coverage-text --coverage-clover=coverage.clover

notifications:
  slack: quartetcom:DcjYF22QWdZMWQ9k1ZyN6zK9
